[2023-08-01T10:56:59.832+0000] {processor.py:154} INFO - Started process (PID=1603) to work on /opt/airflow/dags/group_dag2.py
[2023-08-01T10:56:59.834+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag2.py for tasks to queue
[2023-08-01T10:56:59.835+0000] {logging_mixin.py:120} INFO - [2023-08-01T10:56:59.835+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag2.py
[2023-08-01T10:56:59.859+0000] {logging_mixin.py:120} INFO - [2023-08-01T10:56:59.857+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag2.py", line 15, in <module>
    subdag=subdag_downloads(dag.dag_id, 'downloads', args)
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 9, in subdag_downloads
    chatchup=args['catchup']) as dag:
TypeError: __init__() got an unexpected keyword argument 'chatchup'
[2023-08-01T10:56:59.859+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag2.py
[2023-08-01T10:56:59.875+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag2.py took 0.047 seconds
[2023-08-01T10:57:03.988+0000] {processor.py:154} INFO - Started process (PID=1607) to work on /opt/airflow/dags/group_dag2.py
[2023-08-01T10:57:03.991+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag2.py for tasks to queue
[2023-08-01T10:57:03.993+0000] {logging_mixin.py:120} INFO - [2023-08-01T10:57:03.993+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag2.py
[2023-08-01T10:57:04.033+0000] {logging_mixin.py:120} INFO - [2023-08-01T10:57:04.031+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag2.py", line 15, in <module>
    subdag=subdag_downloads(dag.dag_id, 'downloads', args)
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 9, in subdag_downloads
    chatchup=args['catchup']) as dag:
TypeError: __init__() got an unexpected keyword argument 'chatchup'
[2023-08-01T10:57:04.034+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag2.py
[2023-08-01T10:57:04.052+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag2.py took 0.071 seconds
[2023-08-01T10:57:34.685+0000] {processor.py:154} INFO - Started process (PID=1642) to work on /opt/airflow/dags/group_dag2.py
[2023-08-01T10:57:34.689+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag2.py for tasks to queue
[2023-08-01T10:57:34.690+0000] {logging_mixin.py:120} INFO - [2023-08-01T10:57:34.690+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag2.py
[2023-08-01T10:57:34.721+0000] {logging_mixin.py:120} INFO - [2023-08-01T10:57:34.720+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag2.py", line 15, in <module>
    subdag=subdag_downloads(dag.dag_id, 'downloads', args)
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 9, in subdag_downloads
    chatchup=args['catchup']) as dag:
TypeError: __init__() got an unexpected keyword argument 'chatchup'
[2023-08-01T10:57:34.722+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag2.py
[2023-08-01T10:57:34.738+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag2.py took 0.060 seconds
[2023-08-01T10:58:05.353+0000] {processor.py:154} INFO - Started process (PID=1677) to work on /opt/airflow/dags/group_dag2.py
[2023-08-01T10:58:05.357+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag2.py for tasks to queue
[2023-08-01T10:58:05.359+0000] {logging_mixin.py:120} INFO - [2023-08-01T10:58:05.358+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag2.py
[2023-08-01T10:58:05.390+0000] {logging_mixin.py:120} INFO - [2023-08-01T10:58:05.388+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag2.py", line 15, in <module>
    subdag=subdag_downloads(dag.dag_id, 'downloads', args)
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 9, in subdag_downloads
    chatchup=args['catchup']) as dag:
TypeError: __init__() got an unexpected keyword argument 'chatchup'
[2023-08-01T10:58:05.391+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag2.py
[2023-08-01T10:58:05.407+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag2.py took 0.061 seconds
[2023-08-01T10:58:35.987+0000] {processor.py:154} INFO - Started process (PID=1711) to work on /opt/airflow/dags/group_dag2.py
[2023-08-01T10:58:35.991+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag2.py for tasks to queue
[2023-08-01T10:58:35.992+0000] {logging_mixin.py:120} INFO - [2023-08-01T10:58:35.992+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag2.py
[2023-08-01T10:58:36.023+0000] {logging_mixin.py:120} INFO - [2023-08-01T10:58:36.021+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag2.py", line 15, in <module>
    subdag=subdag_downloads(dag.dag_id, 'downloads', args)
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 9, in subdag_downloads
    chatchup=args['catchup']) as dag:
TypeError: __init__() got an unexpected keyword argument 'chatchup'
[2023-08-01T10:58:36.024+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag2.py
[2023-08-01T10:58:36.040+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag2.py took 0.060 seconds
[2023-08-01T10:59:06.640+0000] {processor.py:154} INFO - Started process (PID=1746) to work on /opt/airflow/dags/group_dag2.py
[2023-08-01T10:59:06.644+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag2.py for tasks to queue
[2023-08-01T10:59:06.645+0000] {logging_mixin.py:120} INFO - [2023-08-01T10:59:06.645+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag2.py
[2023-08-01T10:59:06.669+0000] {logging_mixin.py:120} INFO - [2023-08-01T10:59:06.667+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag2.py", line 15, in <module>
    subdag=subdag_downloads(dag.dag_id, 'downloads', args)
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 9, in subdag_downloads
    chatchup=args['catchup']) as dag:
TypeError: __init__() got an unexpected keyword argument 'chatchup'
[2023-08-01T10:59:06.671+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag2.py
[2023-08-01T10:59:06.688+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag2.py took 0.054 seconds
[2023-08-01T10:59:37.222+0000] {processor.py:154} INFO - Started process (PID=1780) to work on /opt/airflow/dags/group_dag2.py
[2023-08-01T10:59:37.223+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag2.py for tasks to queue
[2023-08-01T10:59:37.225+0000] {logging_mixin.py:120} INFO - [2023-08-01T10:59:37.224+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag2.py
[2023-08-01T10:59:37.243+0000] {logging_mixin.py:120} INFO - [2023-08-01T10:59:37.242+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag2.py", line 15, in <module>
    subdag=subdag_downloads(dag.dag_id, 'downloads', args)
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 9, in subdag_downloads
    chatchup=args['catchup']) as dag:
TypeError: __init__() got an unexpected keyword argument 'chatchup'
[2023-08-01T10:59:37.244+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag2.py
[2023-08-01T10:59:37.258+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag2.py took 0.043 seconds
[2023-08-01T11:00:07.857+0000] {processor.py:154} INFO - Started process (PID=1806) to work on /opt/airflow/dags/group_dag2.py
[2023-08-01T11:00:07.858+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag2.py for tasks to queue
[2023-08-01T11:00:07.858+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:00:07.858+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag2.py
[2023-08-01T11:00:07.875+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:00:07.874+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag2.py", line 15, in <module>
    subdag=subdag_downloads(dag.dag_id, 'downloads', args)
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 9, in subdag_downloads
    chatchup=args['catchup']) as dag:
TypeError: __init__() got an unexpected keyword argument 'chatchup'
[2023-08-01T11:00:07.876+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag2.py
[2023-08-01T11:00:07.891+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag2.py took 0.037 seconds
[2023-08-01T11:00:27.081+0000] {processor.py:154} INFO - Started process (PID=1825) to work on /opt/airflow/dags/group_dag2.py
[2023-08-01T11:00:27.084+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag2.py for tasks to queue
[2023-08-01T11:00:27.085+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:00:27.085+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag2.py
[2023-08-01T11:00:27.122+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:00:27.120+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag2.py", line 15, in <module>
    subdag=subdag_downloads(dag.dag_id, 'downloads', args)
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 9, in subdag_downloads
    chatchup=args['catchup']) as dag:
TypeError: __init__() got an unexpected keyword argument 'chatchup'
[2023-08-01T11:00:27.124+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag2.py
[2023-08-01T11:00:27.140+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag2.py took 0.065 seconds
[2023-08-01T11:00:57.632+0000] {processor.py:154} INFO - Started process (PID=1860) to work on /opt/airflow/dags/group_dag2.py
[2023-08-01T11:00:57.633+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag2.py for tasks to queue
[2023-08-01T11:00:57.634+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:00:57.634+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag2.py
[2023-08-01T11:00:57.669+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:00:57.666+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag2.py", line 15, in <module>
    subdag=subdag_downloads(dag.dag_id, 'downloads', args)
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 9, in subdag_downloads
    chatchup=args['catchup']) as dag:
TypeError: __init__() got an unexpected keyword argument 'chatchup'
[2023-08-01T11:00:57.669+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag2.py
[2023-08-01T11:00:57.688+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag2.py took 0.062 seconds
[2023-08-01T11:01:28.275+0000] {processor.py:154} INFO - Started process (PID=1894) to work on /opt/airflow/dags/group_dag2.py
[2023-08-01T11:01:28.277+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag2.py for tasks to queue
[2023-08-01T11:01:28.279+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:01:28.279+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag2.py
[2023-08-01T11:01:28.303+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:01:28.301+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag2.py", line 15, in <module>
    subdag=subdag_downloads(dag.dag_id, 'downloads', args)
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 9, in subdag_downloads
    chatchup=args['catchup']) as dag:
TypeError: __init__() got an unexpected keyword argument 'chatchup'
[2023-08-01T11:01:28.304+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag2.py
[2023-08-01T11:01:28.324+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag2.py took 0.056 seconds
[2023-08-01T11:01:58.855+0000] {processor.py:154} INFO - Started process (PID=1929) to work on /opt/airflow/dags/group_dag2.py
[2023-08-01T11:01:58.856+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag2.py for tasks to queue
[2023-08-01T11:01:58.861+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:01:58.861+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag2.py
[2023-08-01T11:01:58.881+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:01:58.879+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag2.py", line 15, in <module>
    subdag=subdag_downloads(dag.dag_id, 'downloads', args)
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 9, in subdag_downloads
    chatchup=args['catchup']) as dag:
TypeError: __init__() got an unexpected keyword argument 'chatchup'
[2023-08-01T11:01:58.882+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag2.py
[2023-08-01T11:01:58.897+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag2.py took 0.046 seconds
[2023-08-01T11:02:29.046+0000] {processor.py:154} INFO - Started process (PID=1964) to work on /opt/airflow/dags/group_dag2.py
[2023-08-01T11:02:29.049+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag2.py for tasks to queue
[2023-08-01T11:02:29.050+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:02:29.050+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag2.py
[2023-08-01T11:02:29.079+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:02:29.075+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/group_dag2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/group_dag2.py", line 15, in <module>
    subdag=subdag_downloads(dag.dag_id, 'downloads', args)
  File "/opt/airflow/dags/subdags/subdag_downloads.py", line 9, in subdag_downloads
    chatchup=args['catchup']) as dag:
TypeError: __init__() got an unexpected keyword argument 'chatchup'
[2023-08-01T11:02:29.080+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/group_dag2.py
[2023-08-01T11:02:29.104+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag2.py took 0.063 seconds
[2023-08-01T11:02:47.885+0000] {processor.py:154} INFO - Started process (PID=1980) to work on /opt/airflow/dags/group_dag2.py
[2023-08-01T11:02:47.887+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag2.py for tasks to queue
[2023-08-01T11:02:47.888+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:02:47.888+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag2.py
[2023-08-01T11:02:47.935+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag.downloads', 'group_dag']) retrieved from /opt/airflow/dags/group_dag2.py
[2023-08-01T11:02:48.046+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:02:48.046+0000] {dag.py:2585} INFO - Sync 2 DAGs
[2023-08-01T11:02:48.054+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:02:48.054+0000] {dag.py:2606} INFO - Creating ORM DAG for group_dag.downloads
[2023-08-01T11:02:48.062+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:02:48.062+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2023-07-31T00:00:00+00:00, run_after=2023-08-01T00:00:00+00:00
[2023-08-01T11:02:48.064+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:02:48.064+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2023-08-01T11:02:48.071+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:02:48.071+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2023-08-01T11:02:48.074+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:02:48.074+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2023-08-01T11:02:48.081+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag2.py took 0.201 seconds
[2023-08-01T11:03:02.284+0000] {processor.py:154} INFO - Started process (PID=2000) to work on /opt/airflow/dags/group_dag2.py
[2023-08-01T11:03:02.287+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag2.py for tasks to queue
[2023-08-01T11:03:02.289+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:03:02.288+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag2.py
[2023-08-01T11:03:02.333+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag.downloads', 'group_dag']) retrieved from /opt/airflow/dags/group_dag2.py
[2023-08-01T11:03:02.347+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:03:02.347+0000] {dag.py:2585} INFO - Sync 2 DAGs
[2023-08-01T11:03:02.364+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:03:02.364+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2023-07-31T00:00:00+00:00, run_after=2023-08-01T00:00:00+00:00
[2023-08-01T11:03:02.367+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:03:02.367+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2023-08-01T11:03:02.373+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:03:02.373+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2023-08-01T11:03:02.379+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:03:02.379+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2023-08-01T11:03:02.386+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag2.py took 0.108 seconds
[2023-08-01T11:03:36.370+0000] {processor.py:154} INFO - Started process (PID=33) to work on /opt/airflow/dags/group_dag2.py
[2023-08-01T11:03:36.378+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag2.py for tasks to queue
[2023-08-01T11:03:36.379+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:03:36.378+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag2.py
[2023-08-01T11:03:36.497+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag.downloads', 'group_dag']) retrieved from /opt/airflow/dags/group_dag2.py
[2023-08-01T11:03:36.700+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:03:36.699+0000] {dag.py:2585} INFO - Sync 2 DAGs
[2023-08-01T11:03:36.750+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:03:36.741+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2023-07-31T00:00:00+00:00, run_after=2023-08-01T00:00:00+00:00
[2023-08-01T11:03:36.753+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:03:36.753+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2023-08-01T11:03:36.765+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:03:36.765+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2023-08-01T11:03:36.777+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:03:36.777+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2023-08-01T11:03:36.786+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag2.py took 0.433 seconds
[2023-08-01T11:04:07.517+0000] {processor.py:154} INFO - Started process (PID=68) to work on /opt/airflow/dags/group_dag2.py
[2023-08-01T11:04:07.520+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag2.py for tasks to queue
[2023-08-01T11:04:07.522+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:04:07.522+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag2.py
[2023-08-01T11:04:07.562+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag.downloads', 'group_dag']) retrieved from /opt/airflow/dags/group_dag2.py
[2023-08-01T11:04:07.702+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:04:07.702+0000] {dag.py:2585} INFO - Sync 2 DAGs
[2023-08-01T11:04:07.717+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:04:07.717+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2023-07-31T00:00:00+00:00, run_after=2023-08-01T00:00:00+00:00
[2023-08-01T11:04:07.720+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:04:07.720+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2023-08-01T11:04:07.726+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:04:07.726+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2023-08-01T11:04:07.729+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:04:07.729+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2023-08-01T11:04:07.735+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag2.py took 0.226 seconds
[2023-08-01T11:04:37.868+0000] {processor.py:154} INFO - Started process (PID=103) to work on /opt/airflow/dags/group_dag2.py
[2023-08-01T11:04:37.869+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag2.py for tasks to queue
[2023-08-01T11:04:37.870+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:04:37.870+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag2.py
[2023-08-01T11:04:37.898+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag.downloads', 'group_dag']) retrieved from /opt/airflow/dags/group_dag2.py
[2023-08-01T11:04:37.909+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:04:37.909+0000] {dag.py:2585} INFO - Sync 2 DAGs
[2023-08-01T11:04:37.924+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:04:37.924+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2023-07-31T00:00:00+00:00, run_after=2023-08-01T00:00:00+00:00
[2023-08-01T11:04:37.927+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:04:37.927+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2023-08-01T11:04:37.932+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:04:37.932+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2023-08-01T11:04:37.935+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:04:37.935+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2023-08-01T11:04:37.941+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag2.py took 0.077 seconds
[2023-08-01T11:05:08.839+0000] {processor.py:154} INFO - Started process (PID=139) to work on /opt/airflow/dags/group_dag2.py
[2023-08-01T11:05:08.842+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag2.py for tasks to queue
[2023-08-01T11:05:08.843+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:05:08.843+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag2.py
[2023-08-01T11:05:08.887+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag.downloads', 'group_dag']) retrieved from /opt/airflow/dags/group_dag2.py
[2023-08-01T11:05:09.001+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:05:09.001+0000] {dag.py:2585} INFO - Sync 2 DAGs
[2023-08-01T11:05:09.015+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:05:09.015+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2023-07-31T00:00:00+00:00, run_after=2023-08-01T00:00:00+00:00
[2023-08-01T11:05:09.017+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:05:09.017+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2023-08-01T11:05:09.023+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:05:09.023+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2023-08-01T11:05:09.026+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:05:09.026+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2023-08-01T11:05:09.033+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag2.py took 0.197 seconds
[2023-08-01T11:05:39.913+0000] {processor.py:154} INFO - Started process (PID=173) to work on /opt/airflow/dags/group_dag2.py
[2023-08-01T11:05:39.915+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/group_dag2.py for tasks to queue
[2023-08-01T11:05:39.917+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:05:39.917+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/group_dag2.py
[2023-08-01T11:05:39.953+0000] {processor.py:766} INFO - DAG(s) dict_keys(['group_dag.downloads', 'group_dag']) retrieved from /opt/airflow/dags/group_dag2.py
[2023-08-01T11:05:40.122+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:05:40.122+0000] {dag.py:2585} INFO - Sync 2 DAGs
[2023-08-01T11:05:40.142+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:05:40.142+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag to 2023-07-31T00:00:00+00:00, run_after=2023-08-01T00:00:00+00:00
[2023-08-01T11:05:40.144+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:05:40.144+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2023-08-01T11:05:40.152+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:05:40.152+0000] {dag.py:2585} INFO - Sync 1 DAGs
[2023-08-01T11:05:40.155+0000] {logging_mixin.py:120} INFO - [2023-08-01T11:05:40.155+0000] {dag.py:3340} INFO - Setting next_dagrun for group_dag.downloads to None, run_after=None
[2023-08-01T11:05:40.162+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/group_dag2.py took 0.252 seconds
